CREATE TABLE SC_Topics (
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` varchar(60) NOT NULL UNIQUE,
    `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)