CREATE TABLE IF NOT EXISTS `History`(
    `id` INT AUTO_INCREMENT NOT NULL,
    `user_id` INT NOT NULL,
    `last_arc_id` INT NOT NULL,
    `story_id` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    FOREIGN KEY(user_id) REFERENCES StoryUsers(id) ON DELETE CASCADE,
    UNIQUE KEY(`user_id`, `last_arc_id`, `story_id`)
) CHARACTER SET utf8 COLLATE utf8_general_ci